= Blooming Service Rest Docs
douzone project 5 team
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[Auth]]
== Auth API

=== 회원 가입

operation::employee-auth-controller-test/register[snippets='http-request,request-headers,request-fields,http-response']

=== Employee 삭제

operation::employee-auth-controller-test/delete-employee[snippets='http-request,request-headers,path-parameters,http-response']

=== Employee 수정

operation::employee-auth-controller-test/update-employee[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== Employee No 중복 체크

operation::employee-auth-controller-test/no-check[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== Employee Id 중복 체크

operation::employee-auth-controller-test/id-check[snippets='http-request,request-headers,request-fields,http-response,response-fields']

[[Employee]]
== Employee API

=== Employee 로그인

operation::employee-controller-test/login[snippets='http-request,http-response']

=== Employee 조회

operation::/employee-controller-test/get-employee-by-no[snippets='http-request,request-headers,path-parameters,http-response,response-fields']


=== EmployeeList 조회

operation::/employee-controller-test/find-employee-list[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== Employee 수정

operation::employee-controller-test/update-employee[snippets='http-request,request-headers,path-parameters,http-response']

=== 이미지 조회

operation::employee-controller-test/get-image[snippets='http-request,request-headers,path-parameters,http-response']

=== 이미지 추가

operation::employee-controller-test/add-image[snippets='http-request,request-headers,path-parameters,http-response']

=== 이미지 삭제

operation::employee-controller-test/delete-image[snippets='http-request,request-headers,path-parameters,http-response']

[[Product]]
== Product API

=== Product 추가

operation::/product-controller-test/add-product[snippets='http-request,request-headers,request-fields,http-response']

=== Product 조회

operation::/product-controller-test/get-product[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== Product 리스트 조회

operation::/product-controller-test/get-products[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== Product 수정

operation::/product-controller-test/update-product[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== Product 삭제

operation::/product-controller-test/remove-product[snippets='http-request,request-headers,path-parameters,http-response']

[[Customer]]
== Customer API

=== Customer 추가

operation::customer-controller-test/insert-customer[snippets='http-request,http-response']

=== Customer 조회

operation::customer-controller-test/get-customer[snippets='http-request,path-parameters,http-response,response-fields']

=== CustomerList 조회

operation::customer-controller-test/get-customer-list[snippets='http-request,http-response,response-fields']

=== Customer 수정

operation::customer-controller-test/update-customer[snippets='http-request,path-parameters,http-response']

=== Customer 삭제

operation::customer-controller-test/delete-customer[snippets='http-request,path-parameters,http-response']

[[Instruction]]
== Instruction API

=== Instruction 추가

operation::instruction-controller-test/insert-instruction[snippets='http-request,http-response']

=== Instruction 조회

operation::instruction-controller-test/get-instruction[snippets='http-request,path-parameters,http-response,response-fields']

.ProgressStatus
[cols=2*,options=header]
|===
|Progress_Status
|진행 상태

|Standby
|대기

|Progress
|진행

|Complete
|완료
|===

=== InstructionList 조회

operation::instruction-controller-test/get-instructions[snippets='http-request,http-response,response-fields']

=== Instruction 수정

operation::instruction-controller-test/update-instruction[snippets='http-request,path-parameters,http-response']

=== Instruction 삭제

operation::instruction-controller-test/delete-instruction[snippets='http-request,path-parameters,http-response']