= Blooming Service Rest Docs
douzone project 5 team
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[Auth]]

== Auth API

=== 회원 가입

operation::employee-auth-controller-test/register[snippets='http-request,request-headers,request-fields,http-response']

=== Employee 삭제

operation::employee-auth-controller-test/delete-employee[snippets='http-request,request-headers,path-parameters,http-response']

=== Employee 수정

operation::employee-auth-controller-test/update-employee[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== Employee No 중복 체크

operation::employee-auth-controller-test/no-check[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== Employee Id 중복 체크

operation::employee-auth-controller-test/no-check[snippets='http-request,request-headers,request-fields,http-response,response-fields']

[[Employee]]

== Employee API

=== Employee 로그인

operation::employee-controller-test/login[snippets='http-request,http-response']

=== Employee 조회

operation::/employee-controller-test/get-employee-by-no[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== EmployeeList 조회

operation::/employee-controller-test/find-employee-list[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== Employee 수정

operation::employee-controller-test/update-employee[snippets='http-request,request-headers,path-parameters,http-response']

=== 이미지 조회

operation::employee-controller-test/get-image[snippets='http-request,request-headers,path-parameters,http-response']

=== 이미지 추가

operation::employee-controller-test/add-image[snippets='http-request,request-headers,path-parameters,http-response']

=== 이미지 삭제

operation::employee-controller-test/delete-image[snippets='http-request,request-headers,path-parameters']
[[Product]]
== Product API

=== Product 추가

operation::/product-controller-test/add-product[snippets='http-request,http-response']

=== Product 조회

operation::/product-controller-test/get-product[snippets='http-request,path-parameters,http-response,response-fields']

